<?php

namespace Mybets\ResultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserTeamPowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTeamPowerRepository extends EntityRepository
{
}
