parameters:
#    mybets_user.example.class: Mybets\UserBundle\Example

services:
#    mybets_user.example:
#        class: %mybets_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
